export function createInput({renderer,attack,dodge,interact,usePotion,toggleInv}){
  const keys={},joy={x:0,y:0};let yaw=0,pitch=.38,dragId=null,lastX=0,lastY=0,joyId=null,dodgeLock=0;
  addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys[k]=true;if(e.key===' '){e.preventDefault();attack();}if(k==='e'||k==='f')interact();if(k==='i')toggleInv();if(k==='q')usePotion();if(e.key==='Shift')dodge();});
  addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('blur',()=>Object.keys(keys).forEach(k=>keys[k]=false));
  renderer.domElement.addEventListener('pointerdown',e=>{if(dragId===null){dragId=e.pointerId;lastX=e.clientX;lastY=e.clientY;}});addEventListener('pointermove',e=>{if(e.pointerId!==dragId)return;yaw-=(e.clientX-lastX)*.006;pitch=Math.max(.12,Math.min(.85,pitch-(e.clientY-lastY)*.004));lastX=e.clientX;lastY=e.clientY;});const end=e=>{if(e.pointerId===dragId)dragId=null;};addEventListener('pointerup',end);addEventListener('pointercancel',end);
  const joyEl=document.getElementById('joy'),stick=joyEl.querySelector('.stick');joyEl.addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;try{joyEl.setPointerCapture(e.pointerId)}catch{}moveJoy(e);});joyEl.addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveJoy(e);});const endJoy=e=>{if(e.pointerId!==joyId)return;joyId=null;joy.x=joy.y=0;stick.style.transform='translate(0,0)';};joyEl.addEventListener('pointerup',endJoy);joyEl.addEventListener('pointercancel',endJoy);joyEl.addEventListener('lostpointercapture',endJoy);
  function moveJoy(e){const r=joyEl.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/42,y=(e.clientY-(r.top+r.height/2))/42,l=Math.hypot(x,y);joy.x=l>1?x/l:x;joy.y=l>1?y/l:y;stick.style.transform=`translate(${joy.x*28}px,${joy.y*28}px)`;}
  document.getElementById('attack').addEventListener('pointerdown',e=>{e.preventDefault();attack();});document.getElementById('dodge').addEventListener('pointerdown',e=>{e.preventDefault();dodge();});document.getElementById('interact').addEventListener('pointerdown',e=>{e.preventDefault();interact();});document.getElementById('potion').addEventListener('pointerdown',e=>{e.preventDefault();usePotion();});
  return {keys,joy,get yaw(){return yaw},get pitch(){return pitch},get dodgeLock(){return dodgeLock},set dodgeLock(v){dodgeLock=v}};
}
